coverage:
  status:
    # allow test coverage to drop by 1%, assume that it's typically due to CI problems
    patch:
      default:
        enabled: no
        if_not_found: success
    project:
      default:
        threshold: 1
